# Generated by Django 5.0.3 on 2026-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_preferences_ui"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accesstoken",
            name="access_toke_token_da8eb7_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailtoken",
            name="email_token_token_5dabac_idx",
        ),
        migrations.RemoveIndex(
            model_name="passwordtoken",
            name="password_to_token_a61db7_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_usernam_baeb4b_idx",
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="emailtoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="passwordtoken",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
